FROM python:3.9-slim
WORKDIR /application
COPY . .
ENV DB_USER=app
ENV DB_NAME=virtd
RUN python3 -m venv venv
RUN . venv/bin/activate
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
CMD ["python", "main.py"]



